name: 'Updating English texts and README'
# -- Extract the English texts to the locale/translation.js
# -- Update all the .po files
# -- UPdate the README.md file

# Controls when the action will run. 
on:

# Manual activation
 workflow_dispatch:
  
  # Triggers the workflow on push or pull request events but only for the develop branch
  #push:
  #  branches: [ develop ]
  #pull_request:
  #  branches: [ develop ]

 
# Only one Job
jobs:

  #-- Update the English texts
  update:
    runs-on: ubuntu-20.04

    steps:
      
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
              sudo apt-get install gettext
              pip install icm
              icm --version

      - name: Execute the update script
        run: bash update.sh

            

      
